### ISSUE TITLE
Adding UI won't work

### ISSUE THREAD

**Issue by Mitgenosse** [SkylinesModding/Docs#9]
Hello,
I have an issue with the Adding UI approach. Since I am new to all this unity stuff, I have no Idea how to do a UI. The docs look easy, but it won't work. In my class's (which inherited LoadingExtensionBase) in the OnLevelLoaded(LoadMode mode) Method, I have the following statement:

UIView v = UIView.GetAView();
UIComponent uiComponent = v.AddUIComponent(typeof(ConfigurationPanel)); //exception

Just like in the docs.
The problem is that when I load the map, it thows a null-exception. v is not null, I checked it. if(v != null)...
I cannot understand why it is throwing this error, I hope you can help me.
Or could you tell me a different approach on how to create a UI (I neew a panel with some labels and buttons).

My ConfigurationPanel.cs
class ConfigurationPanel : UIPanel //Testing
    {
        public override void Start()
        {
            Log.MessageUnity("Configuration panel start.");
            SimulationManager.instance.ForcedSimulationPaused = true;
            try
            {
                //Configures this window
                this.backgroundSprite = "GenericPanel";
                this.color = new Color32(255, 0, 0, 100);
                this.width = 300;
                this.height = 500;
                //this.position = new Vector3(Screen.width / 2, Screen.height / 2);
            }
            catch (Exception ex)
            {
                Log.ErrorUnity("ABC" + ex.ToString());
            }
        }
    }

You can also contact me under gurkenschreck@kampfverband-fuchs.de
Thank you for your attention.

**Comment by Dark-Arcana** [comment]
The docs are only for showing information, solutions to problems, faq, etc. The docs and subsequent issues section is not for asking for help with anything related to modding. Use the forum for that.

**Comment by Mitgenosse** [comment]
Adding the (UIComponent)v... helped.
UIComponent uiComponent = (UIComponent)v.AddUIComponent(typeof(ConfigurationPanel));
